---
- name: set sudoers template
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    mode: "0440"
    owner: "root"
    group: "root"
    validate: '/usr/sbin/visudo -cf %s'
  tags:
    - aspects_sudo
    - aspects_sudoers
